# Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Import Data Set and Clean the dataset

In [2]:
data=pd.read_csv('/content/sample_data/ENB2012_data.csv')
data.dropna(how='all') #remove NaN values from the data set
datanew= data.dropna(axis=1, how='all') #first deletes all the non useful columns from the dataset
data_processed=datanew.dropna(how='all') #then deletes all the unuseful rows from the data set
print(data_processed)
#lets try re-naming all the headers columns
data_finalized=data_processed.rename(columns={"X1": "Relative Compactness", "X2": "Surface Area","X3": "Wall Area","X4": "Roof Area","X5": "Overall Height","X6": "Orientation","X7": "Glazing Area","X8": "Glazing Area Distribution","Y1": "Heating Load","Y2":"Cooling Load"})
data_finalized.head(10) #lets me look at random samples within the dataset


       X1     X2     X3      X4   X5   X6   X7   X8     Y1     Y2
0    0.98  514.5  294.0  110.25  7.0  2.0  0.0  0.0  15.55  21.33
1    0.98  514.5  294.0  110.25  7.0  3.0  0.0  0.0  15.55  21.33
2    0.98  514.5  294.0  110.25  7.0  4.0  0.0  0.0  15.55  21.33
3    0.98  514.5  294.0  110.25  7.0  5.0  0.0  0.0  15.55  21.33
4    0.90  563.5  318.5  122.50  7.0  2.0  0.0  0.0  20.84  28.28
..    ...    ...    ...     ...  ...  ...  ...  ...    ...    ...
763  0.64  784.0  343.0  220.50  3.5  5.0  0.4  5.0  17.88  21.40
764  0.62  808.5  367.5  220.50  3.5  2.0  0.4  5.0  16.54  16.88
765  0.62  808.5  367.5  220.50  3.5  3.0  0.4  5.0  16.44  17.11
766  0.62  808.5  367.5  220.50  3.5  4.0  0.4  5.0  16.48  16.61
767  0.62  808.5  367.5  220.50  3.5  5.0  0.4  5.0  16.64  16.03

[768 rows x 10 columns]


Relative Compactness  Surface Area  Wall Area  Roof Area  Overall Height  \
0                  0.98         514.5      294.0     110.25             7.0   
1                  0.98         514.5      294.0     110.25             7.0   
2                  0.98         514.5      294.0     110.25             7.0   
3                  0.98         514.5      294.0     110.25             7.0   
4                  0.90         563.5      318.5     122.50             7.0   
5                  0.90         563.5      318.5     122.50             7.0   
6                  0.90         563.5      318.5     122.50             7.0   
7                  0.90         563.5      318.5     122.50             7.0   
8                  0.86         588.0      294.0     147.00             7.0   
9                  0.86         588.0      294.0     147.00             7.0   

   Orientation  Glazing Area  Glazing Area Distribution  Heating Load  \
0          2.0           0.0                        0.0         15.55   
1          3.0           0.0                        0.0         15.55   
2          4.0           0.0                        0.0         15.55   
3          5.0           0.0                        0.0         15.55   
4          2.0           0.0                        0.0         20.84   
5          3.0           0.0                        0.0         21.46   
6          4.0           0.0                        0.0         20.71   
7          5.0           0.0                        0.0         19.68   
8          2.0           0.0                        0.0         19.50   
9          3.0           0.0                        0.0         19.95   

   Cooling Load  
0         21.33  
1         21.33  
2         21.33  
3         21.33  
4         28.28  
5         25.38  
6         25.16  
7         29.60  
8         27.30  
9         21.97

# Define x and y variables

In [3]:
x=data_finalized.iloc[:,:-2].values
y=data_finalized.iloc[:,9:10].values
print(y)


[[21.33]
 [21.33]
 [21.33]
 [21.33]
 [28.28]
 [25.38]
 [25.16]
 [29.6 ]
 [27.3 ]
 [21.97]
 [23.49]
 [27.87]
 [23.77]
 [21.46]
 [21.16]
 [24.93]
 [37.73]
 [31.27]
 [30.93]
 [39.44]
 [29.79]
 [29.68]
 [29.79]
 [29.4 ]
 [10.9 ]
 [11.19]
 [10.94]
 [11.17]
 [11.27]
 [11.72]
 [11.29]
 [11.67]
 [11.74]
 [12.05]
 [11.73]
 [11.93]
 [12.4 ]
 [12.23]
 [12.4 ]
 [12.14]
 [16.78]
 [16.8 ]
 [16.75]
 [16.67]
 [12.07]
 [12.22]
 [12.08]
 [12.04]
 [26.47]
 [26.37]
 [26.44]
 [26.29]
 [32.92]
 [29.87]
 [29.58]
 [34.33]
 [30.89]
 [25.6 ]
 [27.03]
 [31.73]
 [27.31]
 [24.91]
 [24.61]
 [28.51]
 [41.68]
 [35.28]
 [34.43]
 [43.33]
 [33.87]
 [34.07]
 [34.14]
 [33.67]
 [13.43]
 [13.71]
 [13.48]
 [13.7 ]
 [13.8 ]
 [14.28]
 [13.87]
 [14.27]
 [14.28]
 [14.61]
 [14.3 ]
 [14.45]
 [13.9 ]
 [13.72]
 [13.88]
 [13.65]
 [19.37]
 [19.43]
 [19.34]
 [19.32]
 [14.34]
 [14.5 ]
 [14.33]
 [14.27]
 [25.95]
 [25.63]
 [26.13]
 [25.89]
 [32.54]
 [29.44]
 [29.36]
 [34.2 ]
 [30.91]
 [25.63]
 [27.36]
 [31.9 ]
 [27.38]
 [25.02]
 [24.8 ]
 

In [ ]:
#y = y.reshape(len(y),1) #do this only for feature scaling for Support Vector Regressor mode

# Split data into training and test set

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

# Run this code for applying random forest regression

In [7]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestRegressor(n_estimators=10, random_state=0)

In [8]:
y_pred = regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[17.42 17.63]
 [13.61 13.57]
 [36.72 34.62]
 [23.21 21.16]
 [32.42 33.34]
 [30.04 34.2 ]
 [29.59 30.18]
 [29.06 30.34]
 [33.23 29.82]
 [27.09 24.61]
 [11.34 11.67]
 [39.54 38.35]
 [14.64 14.65]
 [40.82 39.41]
 [44.05 37.7 ]
 [29.25 31.06]
 [14.22 13.87]
 [29.84 34.33]
 [14.62 15.38]
 [15.08 15.4 ]
 [15.58 14.38]
 [32.32 33.13]
 [13.83 14.14]
 [42.92 43.86]
 [11.05 11.17]
 [17.14 17.37]
 [14.01 14.47]
 [16.49 16.69]
 [14.07 14.27]
 [38.18 37.54]
 [14.18 13.97]
 [15.94 16.14]
 [43.24 46.44]
 [15.99 16.22]
 [29.57 29.78]
 [36.66 36.07]
 [16.02 16.08]
 [36.62 36.93]
 [17.07 17.2 ]
 [16.8  16.78]
 [13.93 13.7 ]
 [37.23 36.77]
 [17.27 17.2 ]
 [27.19 26.41]
 [25.02 27.3 ]
 [25.68 26.02]
 [14.03 13.89]
 [15.83 15.17]
 [32.45 32.83]
 [33.34 31.  ]
 [33.   33.94]
 [14.39 14.27]
 [34.01 34.05]
 [17.66 17.64]
 [36.75 37.2 ]
 [13.54 13.7 ]
 [21.77 21.33]
 [27.73 31.39]
 [40.4  37.26]
 [17.12 16.9 ]
 [18.35 18.1 ]
 [14.88 14.91]
 [33.44 33.86]
 [13.41 13.72]
 [15.39 15.85]
 [14.76 14.49]
 [42.89 45

# R^2 value- random forest regression model

In [9]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)
#very good value  r square value

0.9738978364770651

# Decision Tree Regression 

In [10]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(x_train, y_train)


DecisionTreeRegressor(random_state=0)

In [11]:
y_pred = regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[17.04 17.63]
 [13.72 13.57]
 [41.07 34.62]
 [21.46 21.16]
 [33.24 33.34]
 [29.36 34.2 ]
 [29.28 30.18]
 [31.71 30.34]
 [34.52 29.82]
 [25.11 24.61]
 [11.29 11.67]
 [38.84 38.35]
 [14.81 14.65]
 [39.07 39.41]
 [47.01 37.7 ]
 [31.76 31.06]
 [14.3  13.87]
 [29.58 34.33]
 [14.35 15.38]
 [14.94 15.4 ]
 [15.85 14.38]
 [33.24 33.13]
 [13.67 14.14]
 [43.8  43.86]
 [10.94 11.17]
 [16.93 17.37]
 [13.89 14.47]
 [16.62 16.69]
 [13.87 14.27]
 [36.26 37.54]
 [14.24 13.97]
 [16.26 16.14]
 [38.33 46.44]
 [15.87 16.22]
 [29.43 29.78]
 [36.87 36.07]
 [16.11 16.08]
 [37.01 36.93]
 [17.15 17.2 ]
 [16.8  16.78]
 [13.59 13.7 ]
 [36.85 36.77]
 [17.22 17.2 ]
 [26.95 26.41]
 [23.77 27.3 ]
 [25.63 26.02]
 [14.26 13.89]
 [15.99 15.17]
 [33.91 32.83]
 [31.6  31.  ]
 [32.83 33.94]
 [14.33 14.27]
 [33.88 34.05]
 [17.86 17.64]
 [36.87 37.2 ]
 [13.48 13.7 ]
 [21.33 21.33]
 [27.25 31.39]
 [45.52 37.26]
 [17.23 16.9 ]
 [18.36 18.1 ]
 [14.92 14.91]
 [32.83 33.86]
 [13.44 13.72]
 [14.94 15.85]
 [14.73 14.49]
 [45.52 45

# R^2- Decision tree regression

In [12]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9326220216027474

# Polynomial Regression Model

In [20]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree = 8)
x_poly = poly_reg.fit_transform(x_train)
regressor = LinearRegression()
regressor.fit(x_poly, y_train)

LinearRegression()

In [21]:
y_pred = regressor.predict(poly_reg.transform(x_test))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


[[4.73e+20 1.76e+01]
 [2.09e+20 1.36e+01]
 [1.10e+20 3.46e+01]
 [8.15e+19 2.12e+01]
 [1.95e+19 3.33e+01]
 [4.08e+19 3.42e+01]
 [1.95e+19 3.02e+01]
 [8.11e+19 3.03e+01]
 [5.89e+19 2.98e+01]
 [8.07e+19 2.46e+01]
 [2.77e+20 1.17e+01]
 [1.11e+20 3.84e+01]
 [4.72e+20 1.47e+01]
 [1.11e+20 3.94e+01]
 [1.10e+20 3.77e+01]
 [5.86e+19 3.11e+01]
 [2.76e+20 1.39e+01]
 [4.09e+19 3.43e+01]
 [7.79e+20 1.54e+01]
 [2.77e+20 1.54e+01]
 [3.63e+20 1.44e+01]
 [1.94e+19 3.31e+01]
 [2.77e+20 1.41e+01]
 [1.10e+20 4.39e+01]
 [2.09e+20 1.12e+01]
 [2.77e+20 1.74e+01]
 [7.79e+20 1.45e+01]
 [2.08e+20 1.67e+01]
 [2.77e+20 1.43e+01]
 [1.10e+20 3.75e+01]
 [7.77e+20 1.40e+01]
 [4.73e+20 1.61e+01]
 [1.10e+20 4.64e+01]
 [4.73e+20 1.62e+01]
 [1.93e+19 2.98e+01]
 [1.37e+20 3.61e+01]
 [2.09e+20 1.61e+01]
 [1.37e+20 3.69e+01]
 [7.82e+20 1.72e+01]
 [6.11e+20 1.68e+01]
 [4.73e+20 1.37e+01]
 [1.11e+20 3.68e+01]
 [3.64e+20 1.72e+01]
 [8.13e+19 2.64e+01]
 [5.89e+19 2.73e+01]
 [1.93e+19 2.60e+01]
 [2.76e+20 1.39e+01]
 [3.63e+20 1.

# R^2- Polynomial Regression

In [22]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)


-1.2062404115430617e+39

# Multiple Regression Model

In [23]:

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)


LinearRegression()

In [24]:
y_pred = regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[-7.97e+14  1.76e+01]
 [-7.18e+14  1.36e+01]
 [-6.72e+14  3.46e+01]
 [-6.46e+14  2.12e+01]
 [-5.43e+14  3.33e+01]
 [-5.95e+14  3.42e+01]
 [-5.43e+14  3.02e+01]
 [-6.46e+14  3.03e+01]
 [-6.19e+14  2.98e+01]
 [-6.46e+14  2.46e+01]
 [-7.44e+14  1.17e+01]
 [-6.72e+14  3.84e+01]
 [-7.97e+14  1.47e+01]
 [-6.72e+14  3.94e+01]
 [-6.72e+14  3.77e+01]
 [-6.19e+14  3.11e+01]
 [-7.44e+14  1.39e+01]
 [-5.95e+14  3.43e+01]
 [-8.50e+14  1.54e+01]
 [-7.44e+14  1.54e+01]
 [-7.71e+14  1.44e+01]
 [-5.43e+14  3.31e+01]
 [-7.44e+14  1.41e+01]
 [-6.72e+14  4.39e+01]
 [-7.18e+14  1.12e+01]
 [-7.44e+14  1.74e+01]
 [-8.50e+14  1.45e+01]
 [-7.18e+14  1.67e+01]
 [-7.44e+14  1.43e+01]
 [-6.72e+14  3.75e+01]
 [-8.50e+14  1.40e+01]
 [-7.97e+14  1.61e+01]
 [-6.72e+14  4.64e+01]
 [-7.97e+14  1.62e+01]
 [-5.43e+14  2.98e+01]
 [-7.01e+14  3.61e+01]
 [-7.18e+14  1.61e+01]
 [-7.01e+14  3.69e+01]
 [-8.50e+14  1.72e+01]
 [-8.23e+14  1.68e+01]
 [-7.97e+14  1.37e+01]
 [-6.72e+14  3.68e+01]
 [-7.71e+14  1.72e+01]
 [-6.46e+14

# R^2-Multiple Regression Model

In [25]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

-5.28903967977136e+27