In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [20]:
data=pd.read_csv('ENB2012_data.csv')
data.dropna(how='all') #remove NaN values from the data set
datanew= data.dropna(axis=1, how='all') #first deletes all the non useful columns from the dataset
data_processed=datanew.dropna(how='all') #then deletes all the unuseful rows from the data set
print(data_processed)
#lets try re-naming all the headers columns
data_finalized=data_processed.rename(columns={"X1": "Relative Compactness", "X2": "Surface Area","X3": "Wall Area","X4": "Roof Area","X5": "Overall Height","X6": "Orientation","X7": "Glazing Area","X8": "Glazing Area Distribution","Y1": "Heating Load","Y2":"Cooling Load"})
data_finalized.head(10) #lets me look at random samples within the dataset


       X1     X2     X3      X4   X5   X6   X7   X8     Y1     Y2
0    0.98  514.5  294.0  110.25  7.0  2.0  0.0  0.0  15.55  21.33
1    0.98  514.5  294.0  110.25  7.0  3.0  0.0  0.0  15.55  21.33
2    0.98  514.5  294.0  110.25  7.0  4.0  0.0  0.0  15.55  21.33
3    0.98  514.5  294.0  110.25  7.0  5.0  0.0  0.0  15.55  21.33
4    0.90  563.5  318.5  122.50  7.0  2.0  0.0  0.0  20.84  28.28
..    ...    ...    ...     ...  ...  ...  ...  ...    ...    ...
763  0.64  784.0  343.0  220.50  3.5  5.0  0.4  5.0  17.88  21.40
764  0.62  808.5  367.5  220.50  3.5  2.0  0.4  5.0  16.54  16.88
765  0.62  808.5  367.5  220.50  3.5  3.0  0.4  5.0  16.44  17.11
766  0.62  808.5  367.5  220.50  3.5  4.0  0.4  5.0  16.48  16.61
767  0.62  808.5  367.5  220.50  3.5  5.0  0.4  5.0  16.64  16.03

[768 rows x 10 columns]


Relative Compactness  Surface Area  Wall Area  Roof Area  Overall Height  \
0                  0.98         514.5      294.0     110.25             7.0   
1                  0.98         514.5      294.0     110.25             7.0   
2                  0.98         514.5      294.0     110.25             7.0   
3                  0.98         514.5      294.0     110.25             7.0   
4                  0.90         563.5      318.5     122.50             7.0   
5                  0.90         563.5      318.5     122.50             7.0   
6                  0.90         563.5      318.5     122.50             7.0   
7                  0.90         563.5      318.5     122.50             7.0   
8                  0.86         588.0      294.0     147.00             7.0   
9                  0.86         588.0      294.0     147.00             7.0   

   Orientation  Glazing Area  Glazing Area Distribution  Heating Load  \
0          2.0           0.0                        0.0         15.55   
1          3.0           0.0                        0.0         15.55   
2          4.0           0.0                        0.0         15.55   
3          5.0           0.0                        0.0         15.55   
4          2.0           0.0                        0.0         20.84   
5          3.0           0.0                        0.0         21.46   
6          4.0           0.0                        0.0         20.71   
7          5.0           0.0                        0.0         19.68   
8          2.0           0.0                        0.0         19.50   
9          3.0           0.0                        0.0         19.95   

   Cooling Load  
0         21.33  
1         21.33  
2         21.33  
3         21.33  
4         28.28  
5         25.38  
6         25.16  
7         29.60  
8         27.30  
9         21.97

In [21]:
x=data_finalized.iloc[:,:-2].values
y=heating_load_y=data_finalized.iloc[:,8:9].values
print(y)


[[15.55]
 [15.55]
 [15.55]
 [15.55]
 [20.84]
 [21.46]
 [20.71]
 [19.68]
 [19.5 ]
 [19.95]
 [19.34]
 [18.31]
 [17.05]
 [17.41]
 [16.95]
 [15.98]
 [28.52]
 [29.9 ]
 [29.63]
 [28.75]
 [24.77]
 [23.93]
 [24.77]
 [23.93]
 [ 6.07]
 [ 6.05]
 [ 6.01]
 [ 6.04]
 [ 6.37]
 [ 6.4 ]
 [ 6.37]
 [ 6.4 ]
 [ 6.85]
 [ 6.79]
 [ 6.77]
 [ 6.81]
 [ 7.18]
 [ 7.1 ]
 [ 7.1 ]
 [ 7.1 ]
 [10.85]
 [10.54]
 [10.77]
 [10.56]
 [ 8.6 ]
 [ 8.49]
 [ 8.45]
 [ 8.5 ]
 [24.58]
 [24.63]
 [24.63]
 [24.59]
 [29.03]
 [29.87]
 [29.14]
 [28.09]
 [26.28]
 [26.91]
 [26.37]
 [25.27]
 [23.53]
 [24.03]
 [23.54]
 [22.58]
 [35.56]
 [37.12]
 [36.9 ]
 [35.94]
 [32.96]
 [32.12]
 [32.94]
 [32.21]
 [10.36]
 [10.43]
 [10.36]
 [10.39]
 [10.71]
 [10.8 ]
 [10.7 ]
 [10.75]
 [11.11]
 [11.13]
 [11.09]
 [11.16]
 [11.68]
 [11.69]
 [11.7 ]
 [11.69]
 [15.41]
 [15.2 ]
 [15.42]
 [15.21]
 [12.96]
 [12.97]
 [12.93]
 [13.02]
 [24.29]
 [24.31]
 [24.13]
 [24.25]
 [28.88]
 [29.68]
 [28.83]
 [27.9 ]
 [26.48]
 [27.02]
 [26.33]
 [25.36]
 [23.75]
 [24.23]
 [23.67]
 

In [22]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [23]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestRegressor(n_estimators=10, random_state=0)

In [24]:
y_pred = regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[15.17 15.18]
 [10.42 10.32]
 [36.24 37.26]
 [17.02 16.95]
 [32.45 32.26]
 [29.27 27.9 ]
 [28.38 28.18]
 [29.18 28.95]
 [28.81 29.07]
 [23.52 23.8 ]
 [ 6.38  6.4 ]
 [42.67 42.5 ]
 [11.36 11.22]
 [41.96 43.1 ]
 [41.1  41.96]
 [25.67 26.33]
 [10.67 10.7 ]
 [29.36 28.09]
 [14.36 14.65]
 [12.45 12.29]
 [12.69 12.46]
 [32.73 32.71]
 [10.69 10.77]
 [39.41 38.57]
 [ 6.06  6.04]
 [14.64 14.66]
 [12.85 13.  ]
 [13.87 14.41]
 [10.7  10.75]
 [39.77 39.89]
 [12.73 12.74]
 [12.9  12.74]
 [41.74 41.26]
 [12.93 12.77]
 [28.57 28.56]
 [36.92 35.99]
 [14.24 13.97]
 [36.83 35.69]
 [17.13 17.14]
 [10.56 10.85]
 [11.53 11.6 ]
 [39.94 39.97]
 [14.56 14.42]
 [25.87 25.17]
 [18.7  19.5 ]
 [24.29 24.4 ]
 [10.7  13.69]
 [12.7  12.12]
 [28.32 28.86]
 [31.86 32.75]
 [32.55 32.24]
 [12.95 12.97]
 [32.82 32.31]
 [15.14 14.96]
 [36.92 36.95]
 [10.39 10.39]
 [17.7  15.55]
 [27.08 26.19]
 [38.88 40.12]
 [14.53 14.53]
 [14.94 14.72]
 [12.4  12.33]
 [32.46 32.23]
 [10.38 10.34]
 [12.61 12.65]
 [12.15 11.8 ]
 [39.32 38

In [25]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)
#very good value  r square value

0.9968127552656045

In [26]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(x_train, y_train)


DecisionTreeRegressor(random_state=0)

In [27]:
y_pred = regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[15.16 15.18]
 [10.46 10.32]
 [35.48 37.26]
 [17.41 16.95]
 [32.26 32.26]
 [29.05 27.9 ]
 [28.15 28.18]
 [28.67 28.95]
 [28.4  29.07]
 [22.8  23.8 ]
 [ 6.37  6.4 ]
 [41.67 42.5 ]
 [11.34 11.22]
 [41.3  43.1 ]
 [41.09 41.96]
 [26.89 26.33]
 [10.72 10.7 ]
 [29.14 28.09]
 [14.61 14.65]
 [12.45 12.29]
 [12.87 12.46]
 [32.82 32.71]
 [10.66 10.77]
 [38.67 38.57]
 [ 6.01  6.04]
 [14.7  14.66]
 [13.   13.  ]
 [14.19 14.41]
 [10.7  10.75]
 [40.   39.89]
 [12.8  12.74]
 [12.84 12.74]
 [41.64 41.26]
 [13.   12.77]
 [28.57 28.56]
 [36.95 35.99]
 [14.22 13.97]
 [36.95 35.69]
 [17.14 17.14]
 [10.54 10.85]
 [11.59 11.6 ]
 [39.86 39.97]
 [14.58 14.42]
 [26.   25.17]
 [19.95 19.5 ]
 [24.31 24.4 ]
 [10.67 13.69]
 [12.95 12.12]
 [28.03 28.86]
 [31.84 32.75]
 [32.49 32.24]
 [12.93 12.97]
 [33.24 32.31]
 [14.92 14.96]
 [36.95 36.95]
 [10.36 10.39]
 [15.55 15.55]
 [26.97 26.19]
 [38.33 40.12]
 [14.47 14.53]
 [14.9  14.72]
 [12.35 12.33]
 [32.21 32.23]
 [10.37 10.34]
 [12.63 12.65]
 [11.98 11.8 ]
 [39.04 38

In [28]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9966472017174051

In [29]:
from sklearn.preprocessing import StandardScaler
y = y.reshape(len(y),1)
sc_x = StandardScaler()
sc_y = StandardScaler()
x_train = sc_x.fit_transform(x_train)
y_train = sc_y.fit_transform(y_train)

In [30]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree = 8)
x_poly = poly_reg.fit_transform(x_train)
regressor = LinearRegression()
regressor.fit(x_poly, y_train)

LinearRegression()

In [31]:
y_pred = regressor.predict(poly_reg.transform(x_test))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


[[3.95e+20 1.52e+01]
 [1.77e+20 1.03e+01]
 [8.37e+19 3.73e+01]
 [6.25e+19 1.69e+01]
 [1.39e+19 3.23e+01]
 [2.95e+19 2.79e+01]
 [1.39e+19 2.82e+01]
 [6.26e+19 2.89e+01]
 [4.60e+19 2.91e+01]
 [6.27e+19 2.38e+01]
 [2.34e+20 6.40e+00]
 [8.36e+19 4.25e+01]
 [3.95e+20 1.12e+01]
 [8.37e+19 4.31e+01]
 [8.39e+19 4.20e+01]
 [4.61e+19 2.63e+01]
 [2.34e+20 1.07e+01]
 [2.95e+19 2.81e+01]
 [6.41e+20 1.47e+01]
 [2.34e+20 1.23e+01]
 [3.06e+20 1.25e+01]
 [1.39e+19 3.27e+01]
 [2.34e+20 1.08e+01]
 [8.38e+19 3.86e+01]
 [1.77e+20 6.04e+00]
 [2.34e+20 1.47e+01]
 [6.41e+20 1.30e+01]
 [1.77e+20 1.44e+01]
 [2.34e+20 1.08e+01]
 [8.39e+19 3.99e+01]
 [6.42e+20 1.27e+01]
 [3.95e+20 1.27e+01]
 [8.38e+19 4.13e+01]
 [3.95e+20 1.28e+01]
 [1.39e+19 2.86e+01]
 [8.95e+19 3.60e+01]
 [1.77e+20 1.40e+01]
 [8.98e+19 3.57e+01]
 [6.41e+20 1.71e+01]
 [5.06e+20 1.08e+01]
 [3.95e+20 1.16e+01]
 [8.37e+19 4.00e+01]
 [3.06e+20 1.44e+01]
 [6.25e+19 2.52e+01]
 [4.61e+19 1.95e+01]
 [1.39e+19 2.44e+01]
 [2.34e+20 1.37e+01]
 [3.05e+20 1.

In [32]:
#polynomial Regression works best but it might be overfitting the data
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)


-7.016246626717495e+38

In [33]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)


LinearRegression()

In [34]:
y_pred = regressor.predict(x_test)
np.set_printoptions(precision=2)#
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[-2.71e+15  1.52e+01]
 [-2.44e+15  1.03e+01]
 [-2.28e+15  3.73e+01]
 [-2.19e+15  1.69e+01]
 [-1.85e+15  3.23e+01]
 [-2.02e+15  2.79e+01]
 [-1.85e+15  2.82e+01]
 [-2.19e+15  2.89e+01]
 [-2.10e+15  2.91e+01]
 [-2.19e+15  2.38e+01]
 [-2.53e+15  6.40e+00]
 [-2.28e+15  4.25e+01]
 [-2.71e+15  1.12e+01]
 [-2.28e+15  4.31e+01]
 [-2.28e+15  4.20e+01]
 [-2.10e+15  2.63e+01]
 [-2.53e+15  1.07e+01]
 [-2.02e+15  2.81e+01]
 [-2.89e+15  1.47e+01]
 [-2.53e+15  1.23e+01]
 [-2.62e+15  1.25e+01]
 [-1.85e+15  3.27e+01]
 [-2.53e+15  1.08e+01]
 [-2.28e+15  3.86e+01]
 [-2.44e+15  6.04e+00]
 [-2.53e+15  1.47e+01]
 [-2.89e+15  1.30e+01]
 [-2.44e+15  1.44e+01]
 [-2.53e+15  1.08e+01]
 [-2.28e+15  3.99e+01]
 [-2.89e+15  1.27e+01]
 [-2.71e+15  1.27e+01]
 [-2.28e+15  4.13e+01]
 [-2.71e+15  1.28e+01]
 [-1.85e+15  2.86e+01]
 [-2.38e+15  3.60e+01]
 [-2.44e+15  1.40e+01]
 [-2.38e+15  3.57e+01]
 [-2.89e+15  1.71e+01]
 [-2.80e+15  1.08e+01]
 [-2.71e+15  1.16e+01]
 [-2.28e+15  4.00e+01]
 [-2.62e+15  1.44e+01]
 [-2.19e+15

In [35]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

-5.198124312283806e+28